### ISSUE TITLE
Upgrade to ES 5.0.0

### ISSUE THREAD

**Issue by marfago** [dadoonet/spring-elasticsearch#100]
Upgrade to latest Elasticsearch 5.0.0

**Comment by dadoonet** [comment]
It should be compatible. It's not?

**Comment by marfago** [comment]
Unfortunately it is not. I have ported (quite easily) to latest ES 5.0.0 but some tests fail. In partucular NodeBuilder does not exist anymore. I'm not sure, but looks like it is no more possible to build an embedded local ES node.

**Comment by dadoonet** [comment]
I see. Probably we need to get rid of Embedded node as it's not supported by elasticsearch anymore.

**Comment by marfago** [comment]
Added #101 with failing tests.

**Comment by dadoonet** [comment]
I see. Indeed lot of stuff needs to happen.

So here is my plan for now:

* Replace integration tests with what I wrote here: http://david.pilato.fr/blog/2016/10/18/elasticsearch-real-integration-tests-updated-for-ga/
* But this will probably require to write an advanced REST Client on top of the new official Elasticsearch REST Client (I need to think about it. Something similar to https://github.com/dadoonet/fscrawler/tree/master/src/main/java/fr/pilato/elasticsearch/crawler/fs/client but might not be needed though)
* Remove all Node related stuff as described in #96 #103 
* Update to elasticsearch 5.0.x

Not sure when I'll be able to make that happen though.

**Comment by marfago** [comment]
Thank you.
