### ISSUE TITLE
Template not used when ES is restarted

### ISSUE THREAD

**Issue by petrsimon** [dadoonet/spring-elasticsearch#110]
Hi,
I'm using spring-elasticsearch 2.1.0 and ES 2.4.1.
When I start ES and then my server which uses native Java client to create indices, the template is correctly used. 
The problem occurs, when I stop ES while my server is still running, delete all data and indices, restart ES and then create a new index using Java API. 
The index is created without using the template and mapping is incorrect. 
Specifically, I'm using `nested` type, which is missing from the mapping.
Can you please point me in the right direction to find the cause.
Thanks

**Comment by dadoonet** [comment]
Can your share your files?

I mean what you have in es dir?

**Comment by petrsimon** [comment]
Do you mean the data which contain incorrect mapping? It's client's data, so I have to check. 
If I can't share the files, is there another way to move forward?

**Comment by dadoonet** [comment]
I believe that incorrect files would generate some errors in logs. If you can't share the files in public can you DM it?

I have some integration tests which are applying templates so I think it's working but I probably need to check that test code is correct. :)

**Comment by petrsimon** [comment]
Thanks a lot! Sending data to you.

**Comment by dadoonet** [comment]
So after some emails here is actually the situation:

The issue occurs when:

1. start ES, then application
2. stop ES, delete all data
3. start ES (no index exists)
4. at this point _template is empty

Which is normal here as if you don't restart the application, the factory is not restarted so the template is not created.

May be I should expose some utility methods like: https://github.com/dadoonet/spring-elasticsearch/blob/master/src/main/java/fr/pilato/spring/elasticsearch/ElasticsearchAbstractClientFactoryBean.java#L417-L426

So in your code, you could decide if you want to reinitialize it or not...

I need to think about it.

**Comment by petrsimon** [comment]
Thanks a lot! 
A quick solution for me might be to check if template is empty and put it back by
```
node.client().admin().indices().putTemplate(
    new PutIndexTemplateRequest("templatename").source(templateString)
);
```
right?

**Comment by dadoonet** [comment]
Yes. But on the other hand, why would you delete all the data in your cluster?

I'd just remove the indices I don't need anymore.

**Comment by dadoonet** [comment]
BTW your template is not compatible with 5.x series. You need to prepare yourself to upgrade it.

IIRC I saw a `_timestamp` field which is removed I think and also `string` types are moving to `text` or `keyword` types.

**Comment by petrsimon** [comment]
Sure, deleting data is an extreme case. I'm chasing a bug, which lead me to this.
Thanks for the heads up on 5.x series.
