### ISSUE TITLE
Upgrade to Elasticsearch 6.x

### ISSUE THREAD

**Issue by dadoonet** [dadoonet/spring-elasticsearch#124]

**Comment by tianyayoucao** [comment]
Hi dadoonet，it will be really appreciated that the new release version supports Elasticsearch 6.0, for the high-level-rest client has more various funcs，so when can the version be released，do you have the plan，thks！

**Comment by dadoonet** [comment]
I just released a version for elasticsearch 5.x. Finally!

6.x is on its way...
