### ISSUE TITLE
Rejoining a Cluster

### ISSUE THREAD

**Issue by monowai** [dadoonet/spring-elasticsearch#33]
On my dev environment I have a standalone ElasticSearch on 9200 and my own spring app running this project with a client on 9201 to experiment with how clustering behaves. 

I have found during restarts of my app, that spring-es does not join the existing master running on 9200 and instead establishes itself as the master. I have to restart the 9200 instance which successfully joins the master running in my app on 9201.

Can't say I've tried this across physical computers, but it sounds like an issue. 

Running 0.2.0 and ES 0.90.3 on OSX with Java 7

**Comment by dadoonet** [comment]
I'm unsure if this old issue is still an issue?

I'm closing it but feel free to comment here or reopen if you think it's something we should fix in this project.

Best
