### ISSUE TITLE
 Configuration problem: Unable to locate Spring NamespaceHandler for XML schema namespace [http://www.pilato.fr/schema/elasticsearch]

### ISSUE THREAD

**Issue by zouheircadi** [dadoonet/spring-elasticsearch#65]
Hi David,

I'm using your component for elasticSearch access and i have a problem occuring from time to time, preventing server start-up. Most of the time, the server starts. But sometimes, it does not. Partial stack is below 

Caused by: org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Failed to import bean definitions from URL location [classpath:my-es-conf.xml]
févr. 10, 2015 5:06:49 PM org.apache.catalina.core.StandardContext startInternal
Offending resource: class path resource [<theFileWhereMyResource-is imported>]; nested exception is org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Unable to locate Spring NamespaceHandler for XML schema namespace [http://www.pilato.fr/schema/elasticsearch]
GRAVE: Error listenerStart

Don't know if it's really an issue. Any thought about that strange behaviour ?

**Comment by dadoonet** [comment]
Hey Zouheir!

I guess you are doing that on the latest version, right?
Wondering if something is missing in your classpath. Are you trying to run that from your IDE?

Definition is here, so it should work: https://github.com/dadoonet/spring-elasticsearch/blob/master/src/main/resources/META-INF/spring.handlers

May be you could give me more context for this error? Such as Spring version?

**Comment by zouheircadi** [comment]
Hey David, 

No, I'm using the 1.4.0. And the lib is in the classpath. The weird thing is that I'm facing the situation occasionally. 

May be just found the solution here.  : http://www.baeldung.com/unable-to-locate-spring-namespacehandler-for-xml-schema-namespace

For the moment, the problem occurs only when application is started through the IDE. Problem is  probably linked to the classpath refresh of the IDE. 

I think you can close the issue.

**Comment by dadoonet** [comment]
Interesting. Do you think this is something you should fix within your project? Because you are using eclipse?

**Comment by zouheircadi** [comment]
Actually, the IDE is IntelliJ !
