### ISSUE TITLE
Missing schema?

### ISSUE THREAD

**Issue by pierpaolocira** [dadoonet/spring-elasticsearch#69]
Hi, following basic guide on my spring-config.xml Eclipse reports me an error:

> Multiple annotations found at this line:
> 	- cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'elasticsearch:client'.
> 	- schema_reference.4: Failed to read schema document 'http://www.pilato.fr/schema/elasticsearch/elasticsearch-0.3.xsd', because 1) could not find the document; 2) the document could 
	 not be read; 3) the root element of the document is not <xsd:schema>.

In effect either http://www.pilato.fr/schema/elasticsearch/elasticsearch-0.3.xsd nor http://www.pilato.fr exist (there is a 404: "There isn't a GitHub Pages site here" message).

**Comment by dadoonet** [comment]
My bad. I did some changes with my domain name and they have been removed. I'll fix that.

That said, it should work fine although you get this warning.

**Comment by pierpaolocira** [comment]
Yes, it works fine... it was just to adivise you.
PS: thank you for this component... :)

**Comment by dadoonet** [comment]
It's now fixed! Sorry for the delay!
