### ISSUE TITLE
How to connect to a server in openshift

### ISSUE THREAD

**Issue by arrakisdunes** [dadoonet/spring-elasticsearch#70]
hi,

I Have my elasticsearch server in openshift cartidge running on port 80. 

Someone knows how can I connect to this server in port 80? 

Thanks

**Comment by dadoonet** [comment]
It is related to the spring factory project?

**Comment by arrakisdunes** [comment]
Yes. I Would like to know how using this project (how can i do in application context) .

**Comment by dadoonet** [comment]
I think you want to connect using REST layer right?
This project does not provide it as Elasticsearch itself does not provide a REST Java client.

Only Transport and Node clients are available at this moment.

**Comment by arrakisdunes** [comment]
I don't know if it is REST, I only know the only port open to connect is 80.

What could you advise to use to connect then?

Thanks

**Comment by dadoonet** [comment]
I guess that if you run GET / you'll get an answer?
If so it means you have REST Layer running on 80.

Are you using Spring? You might have to create your own singleton on top of JEST?

**Comment by dadoonet** [comment]
No answer since then. Closing.
