### ISSUE TITLE
What version should I use with Elasticsearch 1.7.1?

### ISSUE THREAD

**Issue by rangagopalan** [dadoonet/spring-elasticsearch#71]
We are planning to upgrade our ES servers from 1.4.2 to 1.7.1 - on the client side we are upgrading to the latest 1.7.1 ES client libraries - Is the latest stable version of spring-elasticsearch (1.4.2?) the one that we should use with ES-1.7.1 client?

Please let me know - Thanks

**Comment by dadoonet** [comment]
I did not test it but I guess it should be compatible. Give it a try and report here if you have issues.

**Comment by monowai** [comment]
I’m have no problems with ES 1.7 and spring-elasticsearch.

**Comment by dadoonet** [comment]
That's great! Thanks for confirming @monowai!

I guess changes will be required for 2.0 though.
