### ISSUE TITLE
Could you use commons logging or slf4j for logging instead of log4j directly

### ISSUE THREAD

**Issue by rangagopalan** [dadoonet/spring-elasticsearch#72]
It will be good if this project does not use Log4j directly in the code but uses commons-logging OR slf4j for logging.

I tried to use the latest 1.4.2 version with Elasticsearch 1.7.1 and I  ran into https://github.com/dadoonet/spring-elasticsearch/issues/68 -  The current version has a dependency in the code on Log4j  (e.g. ElasticsearchTransportClientFactoryBean uses log4j org.apache.logging.log4j.LogManager instead of the Apache commons logging org.apache.commons.logging.LogFactory).

Since the earlier version (1.3) used the Commons-logging APIs for logging and that made it easier to integrate into existing larger projects where we could be using either commons-logging or slf4j.

This direct dependency on log4j makes it unusable for me (I'm sticking with version 1.3 for now and that continues to work with elasticsearch 1.7.1 client)

**Comment by dadoonet** [comment]
@rangagopalan Wanna send a PR about it?

**Comment by harrygu** [comment]
I ran into the same issue with 2.0, using slf4j instead of log4j directly could allow more flexibility for integration. In our case, we are using slf4j with logback, introducing log4j is not desired.

**Comment by zackehh** [comment]
@dadoonet I can try find some time to submit a PR for this; would the push to Maven only occur on a new ES version?

**Comment by dadoonet** [comment]
No. I can release a new version anytime.

**Comment by zackehh** [comment]
@dadoonet sweet, I'll start on a PR now - this is definitely the cause of #68, so I have a special interest in this ;)

**Comment by dadoonet** [comment]
Great! Thanks!

**Comment by zackehh** [comment]
@dadoonet here's a PR https://github.com/dadoonet/spring-elasticsearch/pull/78. It should be ok I think, I'm not 100% on what the clash is but it resolved my issue and behaviour is still the same internally. 

There are 3 failing tests on my machine, but they were failing before I changed anything so I just ignored them ;)
