### ISSUE TITLE
node and client bean not created in a java-based spring-configuration

### ISSUE THREAD

**Issue by bsadeh** [dadoonet/spring-elasticsearch#8]
using an xml-based application-context works just fine. however, when creating a java-based application-context (via the `@Configuration` annotation), the esNode and esClient are not initialized correctly; they are null. reason being is that the afterPropertiesSet is not being called yet.

the hack around it for now, is to invoke `factory.afterPropertiesSet()` directly before `factory.getObject()`.
(but that does not feel right)

**Comment by marek-obuchowicz** [comment]
Did anyone involved in this issue figure out how to connect to Elasticsearch cluster in AWS (using spring-data elasticsearch) and NOT specifying esNodes? If we specify the nodes, we don't need the cloud-aws plugin at all...

**Comment by dadoonet** [comment]
@marek-obuchowicz This project is not the spring-data one. Are you sure you are commenting in the right repo?

**Comment by marek-obuchowicz** [comment]
@dadoonet yes, i am aware of that, however it was the only place in the web, where I found someone touching the topic of using spring, elasticsearch TransportClient and cloud-aws. I have been wondering if you can have any tips for my question - if it's possible to use spring+elasticsearch with cloud-aws node discovery, not specifying esNodes (which is, in end, common with spring-data - the client is initialized in the same way)
