### ISSUE TITLE
How to make more flexible control on the Mapping settings ?

### ISSUE THREAD

**Issue by lemon-zmd** [dadoonet/spring-elasticsearch#89]
I am a user of the spring elastic search and it really brings big convenience to me. I now manage the ES mapping settings using a java bean with annotations , but I met the following troubles
1, @Field I can't configure a field name that is not equal to the java variable name. So the name like "a-b" is not accepted.
2,  I want to define the flatten mappings like : 
"index-name": {
      "mappings": {
         "type-name": {
            "_all": {
               "enabled": false
            },
            "properties": {
               "a.displayName": {
                  "type": "string",
                  "index": "not_analyzed"
               },
               "a.realName": {
                  "type": "string",
                  "index": "not_analyzed"
               }, ...
and I want to have the class like : ( because it can really make entity design easier )
@Document(indexName = "index-name", type = "type-name")
public class TDocument {
    static class A{
        @Field(type = FieldType.String, index= FieldIndex.analyzed)
        String displayName;
        @Field(type = FieldType.String, index= FieldIndex.analyzed)
        String realName;
    }
   @Field(type=FieldType.Object)
   A a;
}
Is there anything I can customize?
Thanks a lot !

**Comment by dadoonet** [comment]
I think you are using spring data project, right?

**Comment by lemon-zmd** [comment]
yes, really sorry I made it wrong place.

**Comment by lemon-zmd** [comment]
But if you can give any suggestion that would be great help !!

**Comment by dadoonet** [comment]
I don't know the spring data project :(

**Comment by lemon-zmd** [comment]
Thanks , sorry to bother you. :)
