### ISSUE TITLE
Support plugins for the TransportClient

### ISSUE THREAD

**Issue by timeu** [dadoonet/spring-elasticsearch#90]
I was trying to use the delete-by-query plugin. 
In order to support it from the `TransportClient` the [addPlugin](https://github.com/elastic/elasticsearch/blob/a2b8f4b90a3e8cfa8b816926302c6eb4e38f8ab0/core/src/main/java/org/elasticsearch/client/transport/TransportClient.java#L105) has to be called. 

It would be nice if there would be an easy way to declerative allow to add plugins when using the XML configuration option.

**Comment by dadoonet** [comment]
So I fixed it. But for whatever reason (classloading issue I guess), it does not work when you are using a pure Spring xml file bean definition:

```xml
	<bean id="esClient"
		  class="fr.pilato.spring.elasticsearch.ElasticsearchTransportClientFactoryBean" >
		<property name="esNodes">
			<list>
				<value>localhost:9300</value>
			</list>
		</property>
		<property name="properties" ref="esclientproperties" />
		<property name="classpathRoot" value="/models/plugins/client" />
		<property name="mappings">
			<list>
				<value>twitter/tweet</value>
			</list>
		</property>
		<property name="plugins">
			<set>
				<value>fr.pilato.spring.elasticsearch.Dummy1Plugin</value>
				<value>fr.pilato.spring.elasticsearch.Dummy2Plugin</value>
			</set>
		</property>
	</bean>
```

It works fine when using elasticsearch namespace:

```xml
	<elasticsearch:client id="testTransportClient" esNodes="localhost:9300,localhost:9301" properties="esclientproperties"
						  autoscan="true" forceMapping="false" forceTemplate="false" mergeMapping="false" mergeSettings="false"
						  classpathRoot="/models/transport-client-namespace/client"
	                      plugins="fr.pilato.spring.elasticsearch.plugin.Dummy1Plugin,fr.pilato.spring.elasticsearch.plugin.Dummy2Plugin" />
```

If you have any idea, please feel free to open a PR... :)

**Comment by timeu** [comment]
Great that was quick :thumbsup: thanks 
I was actually using the elasticsearch namespace :wink:
