### ISSUE TITLE
prepareSearch() errors with async created TransportClient

### ISSUE THREAD

**Issue by grd16** [dadoonet/spring-elasticsearch#92]
When I'm trying too use prepareSearch() on TransportClient without any parameters / with more than 1 parameter / or with one templated parameter like esClient.prepareSearch("indexName-*") I got:

_Cannot evaluate org.elasticsearch.common.inject.InjectorImpl.toString()_

This happens only if TransportClient created asynchronously with taskExecutor.

**Comment by dadoonet** [comment]
I created a simple test case and I can't reproduce your issue.
May be you can share your code or check the commit I added to the tests?
