### ISSUE TITLE
Transport Client Properties esNodes and cluster.name

### ISSUE THREAD

**Issue by xuminwlt** [dadoonet/spring-elasticsearch#97]
hi,How can i set Transport Client Properties esNodes and cluster.name both use a util properties?
Like this:
<util:map id="esProperties">
        <entry key="cluster.name" value="newclustername"/>
    </util:map>

    <elasticsearch:client id="esClient" esNodes="#{app.elasticNodes}" properties="esProperties"/>

but,It do not work.
thank you for your answer.

**Comment by xuminwlt** [comment]
<util:map id="esProperties">
        <entry key="cluster.name" value="#{app.clusterName}"/>
    </util:map>
    <elasticsearch:client id="esClient" esNodes="#{app.elasticNodes}" properties="esProperties"/>

properties="esProperties" ide get a warning.but it works now.

**Comment by dadoonet** [comment]
So it works? Closing. Feel free to reopen if I should not have close it.
