### ISSUE TITLE
Release new maven package for ES 2.2.x and update documentation

### ISSUE THREAD

**Issue by marfago** [dadoonet/spring-elasticsearch#98]
In repo there is a commit updating ES dependnecy to version 2.2.0 but documentation still refers to 2.1.x and there is no maven package 2.2.0.

**Comment by dadoonet** [comment]
True. That being said, version for 2.1 should work well...

**Comment by marfago** [comment]
Yes of course. Thank you.

Anyway when using ES 2.1.x or ES 2.2.0 client dependecy on an ES.2.2.1 server threw org.elasticsearch.client.transport.NoNodeAvailableException
Updating dependency to 2.2.1 solved the matter.

**Comment by dadoonet** [comment]
Even without updating, a 2.1 client should be compatible with 2.2. I'm curious about the issue you mentioned before editing your comment. Is it still the case?

**Comment by dadoonet** [comment]
I'm closing but yes I need to release 2.2 because it comes with new features.
See #102
