### ISSUE TITLE
Working with version Spring -elastic 1.4.2 and elastic search 1.7.1

### ISSUE THREAD

**Issue by Vijendra07Kulhade** [dadoonet/spring-elasticsearch#99]
Giving esClient like 

```
<elasticsearch:client id="esClient" esNodes="localhost:9300,localhost:9301" properties="esProperties"/>
```

and esProperties like

```
<util:map id="esProperties">
		<entry key="cluster.name" value="myCluster"/>
</util:map>
```

But getting 

```
None of the configured nodes are available: []
 Caused by: org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []
```

**Comment by dadoonet** [comment]
If you format your code, that'd be easier to read. I updated your question.

Do you have a node running? What is the cluster name?

**Comment by Vijendra07Kulhade** [comment]
Thanks for very quick response.
My Node is running in the same machine. cluster name is myCluster.
I have simply injected this esClient into my Spring component. but it is giving above exceptions during startup only.

**Comment by Vijendra07Kulhade** [comment]
When I am trying to create the client like below I am able to find he running node
```java
Settings settings = ImmutableSettings.settingsBuilder()
                .put("cluster.name","myCluster").build();
        TransportClient client = new TransportClient(settings);
        client.addTransportAddress(new InetSocketTransportAddress("localhost",9300));
```

**Comment by dadoonet** [comment]
@Vijendra07Kulhade Did you manage to solve it?

**Comment by Vijendra07Kulhade** [comment]
Yes It started working for me after I removed all properties. I just gave cluster name in properties.
